SELECT QRCODE, PARTYID, FABRIC, LENTH, FABRICTYP, FPOINT, A.UNITNAME, LLOTNO, DOCID, ORDNO, STYNO, PONO, SNO, LQTY, FABQRDETROW, 
WIDTH, LLOTNO FROM FGMERP.FQRCODEMAS A, QRFABMAS B WHERE  A.DOCID = B.DOCID
AND QRCODE = '00000411001'


INSERT INTO FQRCODEWMSMAS (DOCID, PARTYID, FABRIC, ORDNO, STYNO, PONO, SNO, LQTY, FABQRDETROW, QRCODE, WIDTH, LENTH, 
UNITNAME, STATUS, LLOTNO, BALENO, COMMTR, TOTPOINT, RESULT, REMARKS) VALUES ()


INSERT INTO FQRCODEWMSDEFECT (DOCID, QRCODE, DEFECT, DEFECTPOINT, POINTS) VALUES ()



